import type {
  Booking,
  CrmClient,
  Plan,
  Profile,
  SupportRequest,
} from "../types";
import { PLANS } from "../plans";

// Demo data — professional wellness / therapeutic massage only.
export function seedPlans(): Plan[] {
  return [PLANS.free, PLANS.pro, PLANS.expert];
}

export function seedProfiles(): Profile[] {
  const base = (over: Partial<Profile>): Profile => ({
    id: over.id!,
    user_id: over.user_id ?? null,
    slug: over.slug!,
    full_name: over.full_name!,
    gender: over.gender ?? null,
    show_gender: over.show_gender ?? false,
    years_experience: over.years_experience ?? 0,
    headline: over.headline ?? null,
    professional_description: over.professional_description ?? null,
    safety_boundaries:
      over.safety_boundaries ??
      "Работаю строго в рамках профессионального оздоровительного массажа. Эротический и интимный контент недопустим. Соблюдаю гигиену и профессиональные границы.",
    faq: over.faq ?? [
      { q: "Что взять с собой?", a: "Ничего, всё необходимое предоставляю." },
      { q: "Есть ли противопоказания?", a: "Да, обсуждаем до сеанса. Это не медицинская консультация." },
    ],
    country: "Россия",
    city: over.city ?? null,
    district: over.district ?? null,
    nearest_landmark: over.nearest_landmark ?? null,
    therapist_address_private: over.therapist_address_private ?? "приватный адрес (не публикуется)",
    public_location_label: over.public_location_label ?? null,
    works_at_own_place: over.works_at_own_place ?? false,
    travels_to_client: over.travels_to_client ?? false,
    works_in_hotels: over.works_in_hotels ?? false,
    works_in_villas: over.works_in_villas ?? false,
    works_in_salon: over.works_in_salon ?? false,
    travel_districts: over.travel_districts ?? [],
    minimum_booking_price: over.minimum_booking_price ?? null,
    transport_fee: over.transport_fee ?? null,
    timezone: over.timezone ?? "Europe/Moscow",
    languages: over.languages ?? ["Русский"],
    price_from: over.price_from ?? null,
    session_durations: over.session_durations ?? [60, 90],
    plan_id: over.plan_id ?? "pro",
    is_published: over.is_published ?? true,
    quality_score: over.quality_score ?? 0,
    moderation_status: over.moderation_status ?? "approved",
    created_at: "2026-01-10T10:00:00.000Z",
    updated_at: "2026-04-01T10:00:00.000Z",
    services: over.services ?? [],
    media: over.media ?? [],
  });

  const anna = base({
    id: "11111111-1111-1111-1111-111111111111",
    user_id: "user-anna",
    slug: "anna-kovaleva",
    full_name: "Анна Ковалёва",
    gender: "female",
    show_gender: true,
    years_experience: 9,
    headline: "Лечебно-оздоровительный и расслабляющий массаж",
    professional_description:
      "Дипломированный массажист. Специализируюсь на работе со спиной, шейно-воротниковой зоной и восстановлении после нагрузок. Спокойная атмосфера, индивидуальный подход.",
    city: "Москва",
    district: "Хамовники",
    nearest_landmark: "м. Парк культуры",
    public_location_label: "Москва, центр (Хамовники), рядом с м. Парк культуры",
    works_at_own_place: true,
    travels_to_client: true,
    works_in_hotels: true,
    travel_districts: ["Хамовники", "Арбат", "Якиманка"],
    minimum_booking_price: 3000,
    transport_fee: 500,
    languages: ["Русский", "Английский"],
    price_from: 3000,
    session_durations: [60, 90, 120],
    quality_score: 88,
    services: [
      {
        id: "s-anna-1",
        profile_id: "11111111-1111-1111-1111-111111111111",
        modality: "classic",
        title: "Классический массаж",
        description: "Общий классический массаж тела.",
        duration: 60,
        price: 3000,
        is_published: true,
        sort_order: 0,
      },
      {
        id: "s-anna-2",
        profile_id: "11111111-1111-1111-1111-111111111111",
        modality: "back",
        title: "Массаж спины",
        description: "Проработка спины и поясницы.",
        duration: 45,
        price: 2500,
        contraindication_note: "Не выполняется при острых болях — нужна консультация врача.",
        is_published: true,
        sort_order: 1,
      },
      {
        id: "s-anna-3",
        profile_id: "11111111-1111-1111-1111-111111111111",
        modality: "lymphatic",
        title: "Лимфодренажный массаж",
        description: "Мягкая лимфодренажная техника.",
        duration: 90,
        price: 4500,
        is_published: true,
        sort_order: 2,
      },
    ],
    media: [
      {
        id: "m-anna-1",
        profile_id: "11111111-1111-1111-1111-111111111111",
        type: "profile_photo",
        url: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571",
        alt_text: "Профессиональный массажист Анна",
        sort_order: 0,
        is_published: true,
      },
      {
        id: "m-anna-2",
        profile_id: "11111111-1111-1111-1111-111111111111",
        type: "workspace_photo",
        url: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1",
        alt_text: "Кабинет для массажа",
        sort_order: 1,
        is_published: true,
      },
      {
        id: "m-anna-3",
        profile_id: "11111111-1111-1111-1111-111111111111",
        type: "certificate",
        url: "https://example.com/cert/anna.pdf",
        title: "Диплом массажиста",
        sort_order: 2,
        is_published: true,
      },
      {
        id: "m-anna-4",
        profile_id: "11111111-1111-1111-1111-111111111111",
        type: "intro_video",
        url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        title: "О моей работе",
        sort_order: 3,
        is_published: true,
      },
    ],
  });

  const igor = base({
    id: "22222222-2222-2222-2222-222222222222",
    user_id: "user-igor",
    slug: "igor-sotnikov",
    full_name: "Игорь Сотников",
    gender: "male",
    show_gender: true,
    years_experience: 12,
    headline: "Глубокотканный и спортивный массаж",
    professional_description:
      "Спортивный массажист, работа с триггерными точками, восстановление после тренировок и травм (в рамках оздоровительного массажа, не заменяет врача).",
    city: "Москва",
    district: "Пресненский",
    nearest_landmark: "Москва-Сити",
    public_location_label: "Москва, Пресненский район",
    works_at_own_place: true,
    travels_to_client: true,
    works_in_hotels: true,
    works_in_villas: true,
    travel_districts: ["Пресненский", "Тверской"],
    minimum_booking_price: 4000,
    transport_fee: 700,
    languages: ["Русский", "Английский"],
    price_from: 3500,
    session_durations: [60, 90],
    quality_score: 82,
    services: [
      {
        id: "s-igor-1",
        profile_id: "22222222-2222-2222-2222-222222222222",
        modality: "deep_tissue",
        title: "Глубокотканный массаж",
        description: "Глубокая проработка мышц.",
        duration: 90,
        price: 5000,
        is_published: true,
        sort_order: 0,
      },
      {
        id: "s-igor-2",
        profile_id: "22222222-2222-2222-2222-222222222222",
        modality: "sports",
        title: "Спортивный массаж",
        description: "Восстановление и подготовка к нагрузкам.",
        duration: 60,
        price: 3500,
        is_published: true,
        sort_order: 1,
      },
    ],
    media: [
      {
        id: "m-igor-1",
        profile_id: "22222222-2222-2222-2222-222222222222",
        type: "profile_photo",
        url: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d",
        alt_text: "Массажист Игорь",
        sort_order: 0,
        is_published: true,
      },
      {
        id: "m-igor-2",
        profile_id: "22222222-2222-2222-2222-222222222222",
        type: "diploma",
        url: "https://example.com/cert/igor.pdf",
        title: "Сертификат спортивного массажа",
        sort_order: 1,
        is_published: true,
      },
      {
        id: "m-igor-3",
        profile_id: "22222222-2222-2222-2222-222222222222",
        type: "gallery_photo",
        url: "https://images.unsplash.com/photo-1600334129128-685c5582fd35",
        alt_text: "Процесс массажа",
        sort_order: 2,
        is_published: true,
      },
    ],
  });

  const marina = base({
    id: "33333333-3333-3333-3333-333333333333",
    user_id: "user-marina",
    slug: "marina-petrova-spb",
    full_name: "Марина Петрова",
    gender: "female",
    show_gender: false,
    years_experience: 6,
    headline: "Расслабляющий и антистресс массаж",
    professional_description:
      "Расслабляющие техники, антистресс, массаж для беременных (по согласованию и при отсутствии противопоказаний).",
    city: "Санкт-Петербург",
    district: "Центральный",
    nearest_landmark: "м. Маяковская",
    public_location_label: "Санкт-Петербург, Центральный район",
    works_at_own_place: false,
    travels_to_client: true,
    works_in_hotels: true,
    works_in_salon: true,
    travel_districts: ["Центральный", "Адмиралтейский"],
    minimum_booking_price: 2500,
    transport_fee: 400,
    languages: ["Русский"],
    price_from: 2500,
    session_durations: [60, 90],
    quality_score: 71,
    services: [
      {
        id: "s-marina-1",
        profile_id: "33333333-3333-3333-3333-333333333333",
        modality: "relaxing",
        title: "Расслабляющий массаж",
        description: "Мягкий расслабляющий массаж всего тела.",
        duration: 60,
        price: 2500,
        is_published: true,
        sort_order: 0,
      },
      {
        id: "s-marina-2",
        profile_id: "33333333-3333-3333-3333-333333333333",
        modality: "anti_stress",
        title: "Антистресс массаж",
        description: "Снятие напряжения и стресса.",
        duration: 90,
        price: 3500,
        is_published: true,
        sort_order: 1,
      },
      {
        id: "s-marina-3",
        profile_id: "33333333-3333-3333-3333-333333333333",
        modality: "pregnancy",
        title: "Массаж для беременных",
        description: "Бережный массаж для будущих мам.",
        duration: 60,
        price: 3000,
        contraindication_note:
          "Только при отсутствии противопоказаний и с разрешения наблюдающего врача.",
        is_published: true,
        sort_order: 2,
      },
    ],
    media: [
      {
        id: "m-marina-1",
        profile_id: "33333333-3333-3333-3333-333333333333",
        type: "profile_photo",
        url: "https://images.unsplash.com/photo-1594824476967-48c8b964273f",
        alt_text: "Массажист Марина",
        sort_order: 0,
        is_published: true,
      },
      {
        id: "m-marina-2",
        profile_id: "33333333-3333-3333-3333-333333333333",
        type: "certificate",
        url: "https://example.com/cert/marina.pdf",
        title: "Сертификат",
        sort_order: 1,
        is_published: true,
      },
    ],
  });

  // A draft / low-quality profile (not indexable, used to test gating).
  const draft = base({
    id: "44444444-4444-4444-4444-444444444444",
    user_id: "user-draft",
    slug: "novyy-spetsialist",
    full_name: "Новый специалист",
    years_experience: 1,
    city: "Сочи",
    district: "Центральный",
    plan_id: "free",
    is_published: false,
    moderation_status: "pending",
    quality_score: 25,
    price_from: 2000,
    services: [
      {
        id: "s-draft-1",
        profile_id: "44444444-4444-4444-4444-444444444444",
        modality: "classic",
        title: "Классический массаж",
        duration: 60,
        price: 2000,
        is_published: false,
        sort_order: 0,
      },
    ],
    media: [],
  });

  return [anna, igor, marina, draft];
}

export function seedBookings(): Booking[] {
  return [
    {
      id: "b-1",
      profile_id: "11111111-1111-1111-1111-111111111111",
      token: "demo-booking-token-anna-001",
      client_name: "Екатерина",
      client_role: "self",
      contact_method: "Telegram",
      contact_value: "@ekaterina_demo",
      service_type: "back",
      massage_goal: "Снять напряжение в спине после рабочей недели",
      focus_area: "Поясница, шейно-воротниковая зона",
      pressure_preference: "medium",
      duration: 60,
      location_type: "client_home",
      city: "Москва",
      district: "Арбат",
      address_or_landmark: "ул. Демонстрационная, 1 (приватно)",
      preferred_time_slot_1: "2026-05-20 18:00",
      preferred_time_slot_2: "2026-05-21 19:00",
      preferred_time_slot_3: null,
      confirmed_time_slot: null,
      status: "waiting_therapist_reply",
      outcome: null,
      important_notes: "Бывает чувствительная поясница.",
      created_at: "2026-05-15T09:00:00.000Z",
      updated_at: "2026-05-15T09:00:00.000Z",
      messages: [
        {
          id: "bm-1",
          booking_id: "b-1",
          sender_type: "client",
          sender_name: "Екатерина",
          body: "Здравствуйте! Хочу записаться на массаж спины. Удобно ли в среду вечером?",
          created_at: "2026-05-15T09:00:00.000Z",
          read_at: null,
        },
      ],
      events: [
        {
          id: "be-1",
          booking_id: "b-1",
          event_type: "created",
          event_text: "Заявка создана",
          created_at: "2026-05-15T09:00:00.000Z",
        },
      ],
    },
  ];
}

export function seedClients(): CrmClient[] {
  return [
    {
      id: "c-1",
      profile_id: "11111111-1111-1111-1111-111111111111",
      source_booking_id: null,
      token: "demo-client-token-001",
      name: "Ольга",
      contact_method: "WhatsApp",
      contact_value: "+7 900 000-00-00",
      city: "Москва",
      district: "Хамовники",
      preferred_service_type: "classic",
      pressure_preference: "medium",
      important_notes: "Любит спокойную атмосферу.",
      contraindication_notes: null,
      favorite_duration: 90,
      repeat_status: "repeat",
      created_at: "2026-03-01T10:00:00.000Z",
      updated_at: "2026-04-20T10:00:00.000Z",
      sessions: [
        {
          id: "cs-1",
          client_id: "c-1",
          session_date: "2026-04-20",
          service_type: "classic",
          duration: 90,
          focus_area: "Спина",
          pressure: "medium",
          private_note: "Хорошо отреагировала, рекомендовать раз в 2 недели.",
          next_recommendation: "Повтор через 14 дней",
          created_at: "2026-04-20T12:00:00.000Z",
        },
      ],
    },
  ];
}

export function seedSupport(): SupportRequest[] {
  return [
    {
      id: "sr-1",
      user_id: "user-igor",
      profile_id: "22222222-2222-2222-2222-222222222222",
      name: "Игорь Сотников",
      contact_method: "Telegram",
      contact_value: "@igor_demo",
      preferred_contact_time: "после 18:00",
      topic: "Помочь оформить услуги",
      message: "Нужна помощь с описанием услуг.",
      status: "new",
      admin_note: null,
      created_at: "2026-05-10T09:00:00.000Z",
      updated_at: "2026-05-10T09:00:00.000Z",
    },
  ];
}
